baseURL = "http://sarg.org.ru/"
languageCode = "en-us"
title = "Random forest"
theme = "xmin"
publishDir = "../"
disableKinds = ["RSS", "sitemap", "taxonomy", "term"]

[markup]
  [markup.goldmark.renderer]
  unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "CV"
url = "/cv"
weight = 4

[[menu.main]]
name = "Books"
url = "/books"
weight = 6

[[menu.main]]
name = "Movies"
url = "/movies"
weight = 7
